apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None  # Use None for headless service, allowing pods to connect directly to the service's endpoints
