apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-slave
spec:
  serviceName: "redis-slave"
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
        - name: redis
          image: redis:latest
          command: ["redis-server", "/etc/redis/redis-slave.conf"]
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi