apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    app: redis
    role: sentinel
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    app: redis
    role: sentinel
  clusterIP: None
