apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  redis-master.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
  redis-slave.conf: |
    bind 0.0.0.0
    protected-mode no
    port 6379
    slaveof redis-master 6379
  sentinel.conf: |
    bind 0.0.0.0
    protected-mode no
    port 26379
    sentinel monitor mymaster redis-master.default.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000
